
# this Dockerfile builds a container from which system tests can be run

FROM ubuntu:14.04

ARG PORT

RUN apt-get update && apt-get install -yq curl && apt-get clean

WORKDIR /app

ADD ./system_tests/run_tests.sh /app/run_tests.sh

ENV PORT=${PORT}

CMD ["bash"]
