# A default YAML configuration for the repository.
# Please refer to config_defaults.py for documentation on what these options do

path_patterns:
  '.*': "All paths are valid."

aliases: {}

postprocessors: []

editors: []

username_pattern: '.*'

username_to_name_pattern: ['(?P<username>.*)', '{username}']

username_to_email_pattern: ['(?P<username>.*)', '{username}@example.com']

web_uri_base: ~

required_tooling_version: ~
