# Shared constants

DEBUG = 'debug'
DEV = 'dev'
DOCX = 'docx'
EXTRACT_IMAGES = 'extract_images'
FORMAT_CHECKS = 'format_checks'
GDOC = 'gdoc'
IPYNB = 'ipynb'
KP = 'kp'
LDAP = 'ldap'
MD = 'md'
OAUTH = 'oauth'
ORG = 'org'
PDF = 'pdf'
PROXY = 'proxy'
USERNAME = 'username'
ZIP = 'zip'
