"""Add permissions to posts

Revision ID: f0f4cee14f2a
Revises: 1b385158fd32
Create Date: 2016-11-01 21:44:31.162601

"""

# revision identifiers, used by Alembic.
revision = 'f0f4cee14f2a'
down_revision = '1b385158fd32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_uuid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'posts', sa.Column('special_permissions', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'posts', 'special_permissions')
    op.drop_table('permissions')
    ### end Alembic commands ###
